
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Special Veg Thali', 190,2,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Rice+Dal+Paneer', 190,2,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Raita+Butter Nan', 190,2,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Chhole/Dal+Rice+Mix Veg+Plain Roti', 150,3,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Seasonal Sarso ka saag+Makke ke Roti+Mattha+Gur', 200,3,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Fried Rice/Noodles+Manchurian+Coke', 190,4,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Fried Rice/Noodles+Chilly Paneer+Coke', 200,4,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Veg Manchurian+Fried Rice', 150,4,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Schezwan Fried Rice', 150,4,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Chilli Garlic Fried Rice', 160,4,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Paneer Fried Rice', 180,4,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Mushroom Fried Rice', 160,4,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Kadi+Rice', 140,5,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Rajma+Rice', 120,5,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Chhole+Rice', 120,5,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Battie+Chokha', 60,6,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Battie+Chokha+Dal', 100,6,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Veg Manchow Soup', 70,7,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Veg Sweetcorn Soup', 70,7,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Veg Hot & Sour Soup', 70,7,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Tomato Soup', 60,7,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Chilli Paneer', 180,8,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Chilli Potato', 130,8,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Honey Chilli Potato', 140,8,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Veg Manchurian Dry', 150,8,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Gobhi Manchurian Dry', 150,8,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Veg Hakka Noodles', 130,8,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Veg Noodles/Chowmein', 120,8,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Chilli Soya Chap', 170,8,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Gobhi Manchurian', 160,8,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Veg Manchurian', 160,8,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Paneer Manchurian Gravy', 180,8,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Vegetable Choupsey ', 200,8,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Stuffed Mushroom', 190,9,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Tandoori Mushroom', 180,9,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Mushroom Tikka', 170,9,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Paneer Tikka Masala', 170,9,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Bhatti ka Paneer', 170,9,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Hariyali Paneer Tikka', 170,9,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Malai Paneer Tikka', 180,9,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Paneer Achari Tikka', 170,9,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Dahi ke Kabab', 180,9,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Tandoor Malai Brocoli', 170,9,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Dahi ke Shaley', 170,9,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Badamy Suby Seekh', 170,9,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Tandoori Platter', 220,9,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Hariyali Kabab', 180,9,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Veg Cutlets', 150,9,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Tandoori Soya Chap', 180,10,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Tawa Soya Chap', 180,10,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Tandoori Afgani Chap', 180,10,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Achari Soya Chap', 180,10,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Malai Chap', 200,10,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Shahi Paneer', 200,11,140);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Kadhai Paneer', 180,11,120);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Tawa Paneer Dopayaja', 180,11,120);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Tawa Paneer Butter Masala', 180,11,120);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Tawa Kadhai Paneer', 180,11,120);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Palak Paneer', 190,11,130);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Paneer Burgi', 200,11,190);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Tawa Paneer Bababdar', 180,11,120);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Navratna Korma', 200,11,140);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Methi Malai Paneer', 180,11,120);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Paneer Dhaniya Adraki', 190,11,130);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Paneer Khatta Pyaj', 190,11,130);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Matar Paneer', 180,11,120);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Sarso ka Saag(Seasonal)', 150,11,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Dal Pashtooni(Makhani)', 170,11,90);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Yellow Dal Panchmail', 150,11,90);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Yellow Dal Tadka', 150,11,90);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Dry Urad Dal', 150,11,90);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Dal Palak', 150,11,90);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Pindi Chhole', 150,11,90);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Kadhai Pakoda', 160,11,110);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Rajma Raseela', 150,11,90);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Dum Aaloo', 150,11,90);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Veg Jalfreeji', 160,11,100);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Mix Veg', 160,11,100);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Palak Corn Masala', 160,11,100);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Veg Kofta Masala', 170,11,120);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Malai Kofta', 160,11,120);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Amritsari Wodi Masala', 160,11,100);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Jeera Aaloo', 130,11,100);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Achari Tawa Aaloo', 150,11,100);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Tawa Soya Chap', 180,11,120);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Kadhai Chap', 180,11,120);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Hyderabadi Chap Masala', 190,11,130);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Matar Mushroom', 180,11,120);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Tawa Mushroo Masala', 180,11,120);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Tandoori Roti Plain', 10,12,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Tandoori Roti Butter', 12,12,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Tawa Roti', 10,12,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Chupdi Roti(Desi Ghee)', 15,12,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Lachcha Paratha', 25,12,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Tawa Pudina Paratha', 30,12,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Tawa Methi Paratha', 30,12,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Rumali Roti', 15,12,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Butter Naan', 30,12,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Plain Naan', 20,12,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Butter Garlic Naan', 45,12,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Paneer Naan', 40,12,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Mirchi Paratha Red', 30,12,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Mirchi Paratha Green', 30,12,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Kulcha Aalo', 30,12,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Kulcha Aalo Pyaj', 40,12,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Kulcha Paneer', 50,12,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Kulcha Mix Veg', 50,12,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Plain Rice', 90,13,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Jeera Rice', 100,13,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Matar Pulao', 120,13,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Paneer Pulao', 150,13,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Mushroom Pulao', 160,13,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Navarathna Pulao', 180,13,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Mix Veg Pulao', 150,13,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Kashmiri Pulao', 180,13,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Veg Fried Rice', 130,13,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Veg Biryani', 180,14,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Veg Chap Biryani', 200,14,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Paneer Tikka Biryani', 220,14,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Hyderabadi Dum Biryani', 240,14,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Curd', 50,15,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Plain Raita', 70,15,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Boondi Raita', 80,15,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Mix Raita', 90,15,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Pineapple Raita', 100,15,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Gulab Jamun (2 Piece)', 40,16,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Vanilla Ice Cream', 100,16,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Chocolate Ice Cream', 100,16,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Butterscotch Ice Cream', 100,16,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Mineral Water', 100,17,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Cold Drink', 100,17,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Chaas', 50,17,0);
INSERT INTO menu_items( item_name, price, category_key, half_plate_price) VALUES ('Lassi', 50,17,0);
